development:
  host: localhost
  database: socialize_development

test:
  host: localhost
  database: socialize_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
